# Generated by Django 3.1.4 on 2022-09-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.CharField(help_text='Ex: INF101', max_length=8, primary_key=True, serialize=False, verbose_name='Course Number')),
                ('course_name', models.CharField(max_length=100, verbose_name='Course Name')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(help_text='Ex: Information Technology (BSc) Level 100', max_length=100, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='timetable.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(help_text='Example: JD', max_length=6, verbose_name='Initials')),
                ('full_name', models.CharField(help_text='Example: John Doe', max_length=100, verbose_name='Full Name')),
                ('courses', models.ManyToManyField(blank=True, to='timetable.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_lecturers', to='timetable.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='timetable.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='timetable.programme'),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('6:30 am - 7:30 am', '6:30 am - 7:30 am'), ('7:30 am - 8:30 am', '7:30 am - 8:30 am'), ('8:30 am - 9:30 am', '8:30 am - 9:30 am'), ('9:30 am - 10:30 am', '9:30 am - 10:30 am'), ('10:30 am - 11:30 am', '10:30 am - 11:30 am'), ('11:30 am - 12:30 pm', '11:30 am - 12:30 pm'), ('12:30 pm - 1:30 pm', '12:30 pm - 1:30 pm'), ('1:30 pm - 2:30 pm', '1:30 pm - 2:30 pm'), ('2:30 pm - 3:30 pm', '2:30 pm - 3:30 pm'), ('3:30 pm - 4:30 pm', '3:30 pm - 4:30 pm'), ('4:30 pm - 5:30 pm', '4:30 pm - 5:30 pm'), ('5:30 pm - 6:30 pm', '5:30 pm - 6:30 pm')], default='12:30 - 1:30', max_length=25, verbose_name='Time')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, verbose_name='Day')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_times', to='timetable.course')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetable.venue')),
            ],
            options={
                'unique_together': {('course', 'venue', 'time', 'day')},
            },
        ),
    ]
