# Generated by Django 3.1.4 on 2022-09-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterField(
            model_name='period',
            name='time',
            field=models.CharField(choices=[('6:30 am - 7:30 am', '6:30 am - 7:30 am'), ('7:30 am - 8:30 am', '7:30 am - 8:30 am'), ('8:30 am - 9:30 am', '8:30 am - 9:30 am'), ('9:30 am - 10:30 am', '9:30 am - 10:30 am'), ('10:30 am - 11:30 am', '10:30 am - 11:30 am'), ('11:30 am - 12:30 pm', '11:30 am - 12:30 pm'), ('12:30 pm - 1:30 pm', '12:30 pm - 1:30 pm'), ('1:30 pm - 2:30 pm', '1:30 pm - 2:30 pm'), ('2:30 pm - 3:30 pm', '2:30 pm - 3:30 pm'), ('3:30 pm - 4:30 pm', '3:30 pm - 4:30 pm'), ('4:30 pm - 5:30 pm', '4:30 pm - 5:30 pm'), ('5:30 pm - 6:30 pm', '5:30 pm - 6:30 pm')], default='08:30 am - 09:30 am', max_length=25, verbose_name='Time'),
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
    ]
