# Generated by Django 3.1.4 on 2022-09-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20220913_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='changed',
            field=models.BooleanField(default=False, verbose_name='Rescheduled'),
        ),
    ]
