# Generated by Django 3.1.4 on 2022-09-13 19:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin Access')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=16, region=None, unique=True, verbose_name='phone')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, to='timetable.Course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lecturers', to='timetable.department')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
