# Generated by Django 3.1.4 on 2022-09-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_period_changed'),
        ('user', '0002_auto_20220913_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='timetable.Course'),
        ),
    ]
